name: E2E + Allure -> Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test-and-build-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java (for Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Monocart reporter
        run: npm i -D monocart-reporter@^2.9.21
      - name: Run Playwright tests (Allure + Monocart) and generate Allure report
        run: npm run test:playwright:allure
        env:
          PLAYWRIGHT_EXTENT: '1'

      - name: Stage reports for Pages (Allure + Monocart)
        run: |
          rm -rf pages
          mkdir -p pages/allure
          cp -r allure-report/* pages/allure/
          npm run extent:stage
          # Create a landing index for the root so Pages doesn't 404
          cat > pages/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Test Reports</title>
            <style>
              body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu;line-height:1.5;padding:2rem;max-width:900px;margin:auto}
              h1{margin-top:0}
              ul{padding-left:1.25rem}
              a{color:#0d6efd;text-decoration:none}
              a:hover{text-decoration:underline}
            </style>
          </head>
          <body>
            <h1>Test Reports</h1>
            <ul>
              <li><a href="allure/">Allure Report</a></li>
              <li><a href="extent/">Monocart Report</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload Pages artifact (multi-report)
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

  deploy:
    needs: test-and-build-report
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
